language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS=""
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-5.4
           - g++-5.4
           - valgrind
           - libglew-dev
           - libglfw3-dev
           - libsoil-dev
           - maguey
           - libxrandr-dev
           - libxi-dev
         sources: &precise_latest_boost_sources
           - sourceline: 'ppa:ubuntu-toolchain-r/test'
           - sourceline: 'deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main'
           - sourceline: 'ppa:rdelfin/ppa'
    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - ls -l /usr/lib | grep maguey
    - ls -l /usr/lib/x86_64-linux-gnu | grep libGL.so
    - ls -l /usr/lib/x86_64-linux-gnu | grep libGLU.so
    
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS=${CXX_FLAGS} .. 
     - make
     #- ctest
